source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "logger", "~> 1.5.3"
gem "webrick", "~> 1.9"

group :jekyll_plugins do
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
end
